"""Add new feature

Revision ID: f132ad85ff9e
Revises: 1bcfafe0c1c4
Create Date: 2025-10-15 15:57:02.851556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f132ad85ff9e'
down_revision: Union[str, None] = '1bcfafe0c1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
